### ISSUE TITLE
Pinia Orm Model is not created after the schema updated

### ISSUE THREAD

**Issue by nurielmeni** [quasar-army/lsd-cli#48]
I Used:
```
git@github.com:quasar-army/modular-quasar-template.git
```
blue listens and creates the schema but not the Model.

I followed the Youtube "The Blue Standard 101 - Building Quasar Apps That Scales" for some reason did not generate the Models.

**Comment by nurielmeni** [comment]
I did some digging and found out "bun" was not installed.
```
npm install -g bun
```
Solved the issue

**Comment by ldiebold** [comment]
Hmmm, I probably shouldn't be using bun here, or should add it to deps in the template rather than using it globally. Will have a think about better ways of solving this, but glad you have a solution for now!
